[2025-05-10T00:51:26.645+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:26.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:51:26.650+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:26.687+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:26.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:51:26.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:26.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.082 seconds
[2025-05-10T00:51:57.063+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:57.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:51:57.067+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:57.116+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:51:57.108+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:51:57.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:51:57.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.108 seconds
[2025-05-10T00:52:27.924+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:27.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:52:27.929+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:27.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:27.984+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:27.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:52:27.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:28.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.114 seconds
[2025-05-10T00:52:58.826+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:58.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:52:58.829+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:58.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:58.879+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:52:58.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:52:58.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:52:58.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.129 seconds
[2025-05-10T00:53:29.161+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:53:29.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:53:29.165+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:53:29.199+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:29.192+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:53:29.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:53:29.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.092 seconds
[2025-05-10T00:53:59.949+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:53:59.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:53:59.954+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:59.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:53:59.986+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:53:59.981+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:53:59.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:54:00.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.094 seconds
[2025-05-10T00:54:30.787+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:54:30.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:54:30.790+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:54:30.821+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:54:30.816+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:54:30.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:54:30.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.067 seconds
[2025-05-10T00:55:01.642+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:01.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:55:01.647+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.646+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:01.695+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:01.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:55:01.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:01.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.092 seconds
[2025-05-10T00:55:32.603+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:32.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:55:32.605+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:32.635+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:55:32.627+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:55:32.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:55:32.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.078 seconds
[2025-05-10T00:56:03.311+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:03.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:56:03.319+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.318+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:03.350+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:03.345+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:56:03.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:03.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.075 seconds
[2025-05-10T00:56:34.020+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:34.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:56:34.024+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.024+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:34.057+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:56:34.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:56:34.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:56:34.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.071 seconds
[2025-05-10T00:57:04.886+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:04.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:57:04.889+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:04.888+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:04.919+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:04.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:57:04.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:04.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.062 seconds
[2025-05-10T00:57:35.765+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:35.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:57:35.768+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.767+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:35.797+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:57:35.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:57:35.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:57:35.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.054 seconds
[2025-05-10T00:58:06.476+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:06.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:58:06.479+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:06.499+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:06.495+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:58:06.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:06.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.047 seconds
[2025-05-10T00:58:37.378+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:37.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:58:37.382+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:37.419+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:58:37.413+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:58:37.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:58:37.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.070 seconds
[2025-05-10T00:59:08.288+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:08.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:59:08.295+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:08.338+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:08.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:59:08.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:08.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.105 seconds
[2025-05-10T00:59:39.104+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:39.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T00:59:39.110+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.110+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:39.148+0000] {logging_mixin.py:188} INFO - [2025-05-10T00:59:39.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
ModuleNotFoundError: No module named 'scripts.dataIngestor'
[2025-05-10T00:59:39.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T00:59:39.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.072 seconds
[2025-05-10T01:04:23.639+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:23.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:04:23.650+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:23.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:23.799+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:23.777+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:23.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:23.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.226 seconds
[2025-05-10T01:04:54.281+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:54.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:04:54.285+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:54.340+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:04:54.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:04:54.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:04:54.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.090 seconds
[2025-05-10T01:05:25.285+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:25.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:05:25.288+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:25.349+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:25.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:25.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:25.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.098 seconds
[2025-05-10T01:05:56.348+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:56.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:05:56.352+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:56.417+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:05:56.404+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:05:56.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:05:56.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.105 seconds
[2025-05-10T01:06:27.035+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:27.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:06:27.040+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:27.090+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:27.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:27.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:27.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.085 seconds
[2025-05-10T01:06:57.676+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:57.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:06:57.679+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.678+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:57.745+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:06:57.734+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:06:57.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:06:57.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.103 seconds
[2025-05-10T01:08:09.490+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:09.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:08:09.495+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:09.554+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:09.542+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:09.557+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:09.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.097 seconds
[2025-05-10T01:08:40.235+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:40.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:08:40.237+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:40.294+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:08:40.281+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:08:40.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:08:40.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.094 seconds
[2025-05-10T01:09:11.038+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:11.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:09:11.043+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.043+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:11.102+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:11.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:11.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:11.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.098 seconds
[2025-05-10T01:09:41.761+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:41.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:09:41.764+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:41.806+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:09:41.798+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:09:41.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:09:41.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.080 seconds
[2025-05-10T01:10:12.547+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:12.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:10:12.552+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:12.606+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:12.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:12.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:12.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.083 seconds
[2025-05-10T01:10:43.389+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:43.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:10:43.397+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.396+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:43.488+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:10:43.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:10:43.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:10:43.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.152 seconds
[2025-05-10T01:11:14.244+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:14.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:11:14.250+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:14.322+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:14.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:14.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:14.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.127 seconds
[2025-05-10T01:11:45.048+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:45.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:11:45.053+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.052+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:45.095+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:11:45.086+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:11:45.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:11:45.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.082 seconds
[2025-05-10T01:12:15.796+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:15.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:12:15.799+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:15.799+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:15.850+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:15.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 3, in <module>
    from db.mssqlClient import connect_to_mssql
ModuleNotFoundError: No module named 'db'
[2025-05-10T01:12:15.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:15.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.083 seconds
[2025-05-10T01:12:46.673+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:46.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:12:46.676+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:46.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:47.104+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:12:47.095+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from dataGenerator import generate_all_data
ModuleNotFoundError: No module named 'dataGenerator'
[2025-05-10T01:12:47.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:12:47.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.458 seconds
[2025-05-10T01:13:17.716+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:17.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:13:17.723+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:17.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:18.016+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:18.000+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from dataGenerator import generate_all_data
ModuleNotFoundError: No module named 'dataGenerator'
[2025-05-10T01:13:18.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:18.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.340 seconds
[2025-05-10T01:13:48.509+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:48.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:13:48.512+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.512+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:48.824+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:13:48.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:13:48.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:13:48.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.342 seconds
[2025-05-10T01:14:19.423+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:19.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:14:19.426+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:19.426+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:19.689+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:19.673+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:14:19.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:19.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.305 seconds
[2025-05-10T01:14:50.476+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:50.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:14:50.481+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:50.481+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:50.761+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:14:50.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:14:50.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:14:50.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.350 seconds
[2025-05-10T01:15:44.161+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:15:44.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:15:44.168+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:44.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:15:44.687+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:15:44.667+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:15:44.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:15:44.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.572 seconds
[2025-05-10T01:16:14.924+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:14.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:16:14.944+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:14.940+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:15.369+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:15.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:16:15.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:15.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.483 seconds
[2025-05-10T01:16:46.119+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:46.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:16:46.122+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:46.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:46.314+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:16:46.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:16:46.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:16:46.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.222 seconds
[2025-05-10T01:17:16.740+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:17:16.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:17:16.749+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:16.748+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:17:17.055+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:17:17.033+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_2_data_ingestor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_2_data_ingestor.py", line 5, in <module>
    from scripts.dataIngestor import data_ingestor_mssql, data_ingestor_mysql, data_ingestor_oracle, data_ingestor_postgresql, data_ingestor_sqlite
  File "/opt/airflow/scripts/dataIngestor.py", line 9, in <module>
    from scripts.dataGenerator import generate_all_data
  File "/opt/airflow/scripts/dataGenerator.py", line 5, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2025-05-10T01:17:17.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:17:17.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.373 seconds
[2025-05-10T01:18:48.164+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:18:48.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:18:48.168+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:48.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:18:48.751+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:18:48.975+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:48.975+0000] {override.py:1901} INFO - Created Permission View: can read on DAG:dag_2_data_ingestor
[2025-05-10T01:18:48.991+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:48.991+0000] {override.py:1901} INFO - Created Permission View: can edit on DAG:dag_2_data_ingestor
[2025-05-10T01:18:49.004+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.003+0000] {override.py:1901} INFO - Created Permission View: can delete on DAG:dag_2_data_ingestor
[2025-05-10T01:18:49.005+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.005+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:18:49.023+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.022+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_2_data_ingestor
[2025-05-10T01:18:49.024+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:18:49.024+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:18:49.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.891 seconds
[2025-05-10T01:19:19.309+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:19.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:19:19.312+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.312+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:19.596+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:19.621+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.620+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:19.641+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:19.640+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:19:19.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.356 seconds
[2025-05-10T01:19:50.286+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:50.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:19:50.297+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:50.532+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:19:50.542+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.542+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:19:50.553+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:19:50.553+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:19:50.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.294 seconds
[2025-05-10T01:20:21.037+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:21.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:20:21.041+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:21.295+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:21.384+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.383+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:21.393+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:21.393+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:20:21.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.384 seconds
[2025-05-10T01:20:51.555+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:51.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:20:51.559+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.558+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:51.850+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:20:51.887+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.887+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:20:51.900+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:20:51.900+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:20:51.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.371 seconds
[2025-05-10T01:21:22.466+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:22.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:21:22.471+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:22.778+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:22.790+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.790+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:22.807+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:22.807+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:21:22.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.383 seconds
[2025-05-10T01:21:53.076+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:53.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_2_data_ingestor.py for tasks to queue
[2025-05-10T01:21:53.079+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.079+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:53.376+0000] {processor.py:840} INFO - DAG(s) 'dag_2_data_ingestor' retrieved from /opt/airflow/dags/dag_2_data_ingestor.py
[2025-05-10T01:21:53.492+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.491+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T01:21:53.502+0000] {logging_mixin.py:188} INFO - [2025-05-10T01:21:53.502+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_2_data_ingestor to None, run_after=None
[2025-05-10T01:21:53.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_2_data_ingestor.py took 0.453 seconds
